[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = '#1d1f21'
foreground = '#c5c8c6'

[colors.normal]
black   = '#1d1f21'
red     = '#cc342b'
green   = '#198844'
yellow  = '#fba922'
blue    = '#3971ed'
magenta = '#a36ac7'
cyan    = '#3971ed'
white   = '#c5c8c6'

[colors.bright]
black   = '#969896'
red     = '#cc342b'
green   = '#198844'
yellow  = '#fba922'
blue    = '#3971ed'
magenta = '#a36ac7'
cyan    = '#3971ed'
white   = '#ffffff'

[env]
TERM = "alacritty"

[font]
builtin_box_drawing = true
size = 10.0

[font.normal]
family = "JetBrains Mono"

[window]
opacity = 0.95
